model_list:
  - model_name: local-ollama # Example name, can be anything
    litellm_params:
      # Route any request for 'local-ollama' to the 'ollama' service
      # defined in docker-compose.yml, using the 'mistral' model.
      # Replace 'mistral' if you use a different default model in Ollama.
      model: ollama/mistral
      api_base: http://ollama:11434

litellm_settings:
  drop_params: True # Drop unsupported parameters
  num_retries: 3
  request_timeout: 600 # Default request timeout
  telemetry: False # Disable telemetry

general_settings:
  # Use master key from environment variable
  master_key: os.environ/LITELLM_MASTER_KEY
  # Use database URL from environment variable
  database_url: os.environ/DATABASE_URL
  store_model_in_db: True # Store model info in DB (requires postgres service)

# Removed router_settings, finetune_settings, files_settings, pass_through_endpoints
# Removed all other models from model_list
